### PR TITLE
update ios 6.14.0

### LINKED ISSUE #538: privacy manifest for third part sdk
# Report

Could you please provide Privacy Manifest support for appsflyer SDK? Some relevant links as follows:

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
https://stackoverflow.com/questions/78163859/itms-91053-missing-api-declaration-privacy

Thank you!

## Plugin Version

ℹ Please replace these two lines with the plugin version.
6.13.0

## On what Platform are you having the issue?
React Native
iOS

## What did you do?
N/A
## What did you expect to happen?
N/A

## What happened instead?
N/A

## Please provide any other relevant information.
Linked above

### PR DESCRIPTION
**Pull request by jscarmona**
Closes #538

### CODE REVIEW

**Comment by alhassanreem** [comment]
thank you @jscarmona! @amit-kremer93 would appreciate your review on this when you get a chance

**Comment by briang123** [comment]
Any indication as to when this might be merged in for the Apple Privacy mandate on May 1?

**Comment by alhassanreem** [comment]
@morisgateno-appsflyer can you please take a look here

**Comment by alhassanreem** [comment]
looks like the iOS AppsFlyer SDK has been upgraded through #546

**Pull request closed without merging**
