### PR TITLE
Update Android SDK to `v6.12.2` and iOS SDK to `v6.12.1`

### PR DESCRIPTION
**Pull request by reichhartd**
Bumped the SDK version mainly to include the Android fix https://github.com/AppsFlyerSDK/appsflyer-android-app/issues/20, which was released in `v6.12.2`.
This PR should also resolve https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/464

### CODE REVIEW

**Comment by reichhartd** [comment]
@amit-kremer93 Would really appreciate it if the PR could be reviewed, merged and released soon 🙏

**Comment by lhr000lhr** [comment]
can we release it now?

**Comment by stevechanvii** [comment]
Please update ASAP, thank you

**Comment by mmkhmk** [comment]
I would greatly appreciate it if this is released ASAP 🙏

**Review by sbt-peds — APPROVED** [review]

**Comment by danielmorbeck** [comment]
Any updates on this? Would appreciate if this is released

**Comment by amit-kremer93** [comment]
We released a new version today: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/releases/tag/6.12.2

**Pull request closed without merging**
